<a href="https://colab.research.google.com/github/hongqin/quantum_sandbox/blob/main/complex_numbers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Define two complex vectors
vector1 = np.array([1 + 2j, 3 + 4j])
vector2 = np.array([5 + 6j, 7 + 8j])

# Compute the inner product using the np.vdot() function
inner_product = np.vdot(vector1, vector2)

print(f"The inner product of the vectors is: {inner_product}")


The inner product of the vectors is: (70-8j)


In [ ]:
import numpy as np

# Define a real value for x (in radians)
x = np.pi / 4

# Calculate the left side of Euler's formula (exponential form)
exp_form = np.exp(1j * x)

# Calculate the right side of Euler's formula (trigonometric form)
trig_form = np.cos(x) + 1j * np.sin(x)

# Print both forms
print(f"Euler's exponential form (e^(ix)): {exp_form}")
print(f"Euler's trigonometric form (cos(x) + i*sin(x)): {trig_form}")

# Check if both forms are consistent
if np.isclose(exp_form, trig_form):
    print("Both forms are consistent!")
else:
    print("Both forms are not consistent!")


Euler's exponential form (e^(ix)): (0.7071067811865476+0.7071067811865475j)
Euler's trigonometric form (cos(x) + i*sin(x)): (0.7071067811865476+0.7071067811865475j)
Both forms are consistent!


# Example of complex matrix multiplication

In [6]:
A = np.array([[3 + 2j, 0, 5 - 6j],
              [1,  4 + 2j,  1j],
              [4-1j, 0, 4]])

B = np.array([[5, 2- 1j, 6 - 4j],
              [0,  4 + 5j,  2],
              [7-4j, 2+7j, 0]])


In [7]:
np.dot(A,B)

array([[26.-52.j, 60.+24.j, 26. +0.j],
       [ 9. +7.j,  1.+29.j, 14. +0.j],
       [48.-21.j, 15.+22.j, 20.-22.j]])

In [16]:
import numpy as np
from scipy.linalg import hadamard
H = hadamard(2)
H
np.dot(H, H)

array([[2, 0],
       [0, 2]])

In [19]:
H = ( 1/np.sqrt(2) )* np.array( [[1, 1],
                            [1, -1]])
H
np.dot(H, H)

array([[ 1.00000000e+00, -2.23711432e-17],
       [-2.23711432e-17,  1.00000000e+00]])

In [11]:
np.sqrt(4)

2.0

In [3]:
import numpy as np

def is_hermitian(matrix):
    # Conjugate transpose (Hermitian transpose) of the matrix
    conjugate_transpose = np.conj(matrix).T

    # Check if the original matrix is equal to its conjugate transpose
    #return np.array_equal(matrix, conjugate_transpose)
    return np.allclose(matrix, conjugate_transpose) #for floating point

# Example usage
A = np.array([[3.5, 2 + 1j],
              [2 - 1j, 1]])

if is_hermitian(A):
    print("The matrix is Hermitian.")
else:
    print("The matrix is not Hermitian")


The matrix is Hermitian.
